### ISSUE TITLE
Export -> Make filtered Xi Url not working

### ISSUE THREAD

**Issue by gieses** [Rappsilber-Laboratory/xiView_container#15]
I tried to share a search with somebody (is this actually supposed to work without logging in?) but the link only shows an error message (also for me). 

The URL is: https://xiview.org/xi3/network.php?FmanualMode=1&FfdrMode=0&Flinears=0&Fcrosslinks=1&FbetweenLinks=1&FselfLinks=1&FhomomultimericLinks=1&Fambig=1&FaaApart=0&FpepLength=1&FA=1&FB=1&FC=1&FQ=1&Funval=0&FAUTO=1&Fdecoys=0&FfdrThreshold=0.05&FinterFdrCut=&FintraFdrCut=&FpepSeq=&FprotNames=&Fcharge=&FrunName=&FscanNumber=&FurpPpi=1&FmatchScoreCutoff=%5B0,21%5D

The error is:

> Error when attempting to load search.
Query failed: ERROR: invalid input syntax for integer: "" LINE 1: SELECT * FROM uploads WHERE id = ''; ^

We are going to upload the data for the next paper in XiView. It's two searches, is there anything from your side that speaks against it / needs to be done? 

Thanks.

**Comment by martingraham** [comment]
Looks like a bug in that the search id is nowhere in that url

On 19 Aug 2018 08:44, Sven Giese <notifications@github.com> wrote:

I tried to share a search with somebody (is this actually supposed to work without logging in?) but the link only shows an error message (also for me).

The URL is: https://xiview.org/xi3/network.php?FmanualMode=1&FfdrMode=0&Flinears=0&Fcrosslinks=1&FbetweenLinks=1&FselfLinks=1&FhomomultimericLinks=1&Fambig=1&FaaApart=0&FpepLength=1&FA=1&FB=1&FC=1&FQ=1&Funval=0&FAUTO=1&Fdecoys=0&FfdrThreshold=0.05&FinterFdrCut=&FintraFdrCut=&FpepSeq=&FprotNames=&Fcharge=&FrunName=&FscanNumber=&FurpPpi=1&FmatchScoreCutoff=%5B0,21%5D

The error is:

Error when attempting to load search.
Query failed: ERROR: invalid input syntax for integer: "" LINE 1: SELECT * FROM uploads WHERE id = ''; ^

We are going to upload the data for the next paper in XiView. It's two searches, is there anything from your side that speaks against it / needs to be done?

Thanks.

**Comment by colin-combe** [comment]
> Looks like a bug in that the search id is nowhere in that url

Yes, I have broken it in xiView. Thanks for bug report, will fix.

> We are going to upload the data for the next paper in XiView. It's two searches, is there anything from your side that speaks against it / needs to be done?

It should be OK. It could do with more testing cause there might be other things like above. I plan to give it a proper test when I add some updated documentation that Martin has been working on.

(@martingraham - I'll take doing documentation on the filtering to be on me)

**Comment by gieses** [comment]
@colin-combe sorry, another question. Speaks anything against sharing the link as:
>>https://xiview.org/xi3/network.php?upload=35-49786-17881-94522-79322
? The ultra long link does not fit very well in a printed document.
