### ISSUE TITLE
display 'monolinks' (linker modified peptides)

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/xiView_container#19]
as xiNET at crosslinkviewer.org does

**Comment by colin-combe** [comment]
further user requests for this.
(Not having it blocks people from moving from xiNET to xiView.)

**Comment by colin-combe** [comment]
also https://github.com/Rappsilber-Laboratory/XiSearch/issues/43

**Comment by lutzfischer** [comment]
How do you detect "mono-links"?

**Comment by colin-combe** [comment]
omit LinkPos2 in uploaded CSV, 
same as here http://crosslinkviewer.org/CLMS-CSV.php#productTypes

can you see any problems with this?

there's currently no way of doing it with mzId

i need to update documentation about CSV format on xiView website

**Comment by colin-combe** [comment]
loop links are not yet implemented as they were in http://crosslinkviewer.org/CLMS-CSV.php#productTypes

**Comment by lutzfischer** [comment]
Xi does not write a monolink as such but just writes the cross-linker as a modification into the file. So I was wondering if one could provide a list of modifications to display like that?

**Comment by colin-combe** [comment]
yes, its always been something that's used by people using search software other than xi

you should be able to include things displayed like that by providing CSV files in which there's no LinkPos2

**Comment by colin-combe** [comment]
i think i've misinterpreted you - you'll be asking for an automated way of doing it on basis of whats already in xi output?

**Comment by lutzfischer** [comment]
No. I am basically asking for some means to flag observed modifications.

Meaning to provide a lsit of modifications found in the CSV/mzIdentML and let the user select some to be flagged on the protein-sequence.

That could be usefull beyond monolinks
