### ISSUE TITLE
can click submit while still uploading peaks

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/xiView_container#2]

**Comment by martingraham** [comment]
I can do that in the xi3 search submit page too

It needs an acquisition and sequence already selected for the submit button to be enabled

Then start uploading a big ol' acquisition file

Then press submit before it finishes

End result seems to be the files don't make it and the acquisiton record doesn't get added to the database

I'll have a think and see what's best, either
1) Disable submit button while uploading
2) Have an extra step that says "are you sure, you're still uploading" if you pres submit and it's the case

**Comment by colin-combe** [comment]
yes... we have different bits of code with same problem (mine lives in my xiNET_website project).

2 isn't an option for me, it will definitely be broken if they proceed. It'll be 1 for the xiView website
