### ISSUE TITLE
parsing of modifications during upload

### ISSUE THREAD

**Issue by pdcharles** [Rappsilber-Laboratory/xiView_container#23]
I have encountered a bug when uploading peptide sequences in the csv-based formats.  If a peptide sequence contains multiple modification codes (i.e. lower case notations) then only the first modification from each peptide is parsed for the purposes of determining which modifications are then displayed in the post-upload dialog requesting modification masses. If a modification is never the first listed in any of the peptide sequences (this bug first encountered when uploading a single crosslink where PepSeq1 contained multiple modifications), then the user is never asked to supply a mass for it and this causes spectral annotation to fail (among other issues).

**Comment by colin-combe** [comment]
Thank you for this bug report and your excellent work tracking down the problem.

I've merged your pull request (#56).

Is xiView now working correctly for you?

I've updated this 'xiView_container' project also, which is intended to provide everything needed to create your own local installation of xiView. Setting it up is still a bit tricky, the main problem is the stuff for user account creation. There's a short cut you might find for quickly getting it to work, which is disabling user authentication.

Anyway, please let us know if you have any other problems,
best wishes,
Colin

**Comment by pdcharles** [comment]
Confirming that the bug is now resolved (test case - a minimal version of the example file 'PolII_XiVersion1.6.742_PSM_xiFDR1.1.27.csv' containing only line 13, where PepSeq1 is 'EKbs3nh2GPQVCcmAKLFGNIQK').  Previously, uploading this file only prompted for the 'bs3nh2' mod mass, but now it also correctly asks for the 'cm' mod mass was well.

Cheers!
Phil
