### ISSUE TITLE
mzIdentML PeptideEvidence.isDecoy  is ignored

### ISSUE THREAD

**Issue by lutzfischer** [Rappsilber-Laboratory/xiView_container#32]
Looks like currently decoys are not recognised when read in from an mzIdentML-file.
The file I uploaded had peptideevidences marked as decoy but all matches where displayed and none marked as decoy.

  <PeptideEvidence dBSequence_ref="dbseq_P02768_decoy" peptide_ref="56_TCcmVADESAENCcmDK_134_FNEEGLDKFR_7_8_p1" start="567" end="576" **_isDecoy="true"_** id="pepevid_pep_134_FNEEGLDKFR_protP02768_decoy_567_pepkey_1_56_TCcmVADESAENCcmDK_134_FNEEGLDKFR_7_8_p0_56_TCcmVADESAENCcmDK_134_FNEEGLDKFR_7_8_p1"></PeptideEvidence>

**Comment by colin-combe** [comment]
OK, thanks - could you share the whole file with me somehow (slack might work)
