### ISSUE TITLE
create account fails

### ISSUE THREAD

**Issue by jayieh** [Rappsilber-Laboratory/xiView_container#65]
Hi Rappsilber lab,

I was about to create an account on the xiVIEW website. This has failed on several browsers/machines (Chrome on Win 10 and Server and IE on Win server namely).

{"status":"fail","field":"recaptchaWidget","error":"Input validation failed"}

is the error I get - the captcha, that is shown in the tutorial video is not appearing either...

**Comment by colin-combe** [comment]
Thank you for the error report.

I think this has been broken for about 3 weeks, though the error would have been different prior to today.

I'll let you know when its fixed,
Colin

**Comment by colin-combe** [comment]
Hi jayieh
- is it working again?

The registration process is rather tedious, with google captcha to fill out and confirmation links in emails to click, etc. It could do with being tidied up.

Anyway, I think its working again now. Let me know if not,
cheers,
Colin

**Comment by jayieh** [comment]
Hi Colin,

works like a charm!

Thanks for the instant fix!

Best

Juergen
