### ISSUE TITLE
filter by scan name not working

### ISSUE THREAD

**Issue by wendscheck** [Rappsilber-Laboratory/xiView_container#67]
I'm trying to filter my data by the run name, but sadly whatever i type in the field the data is not filtered. Thanks for you help!

**Comment by colin-combe** [comment]
yep - its broken.
I'll let you know when its fixed,
colin

**Comment by wendscheck** [comment]
That would be great. 
Thanks,
Daniel

**Comment by colin-combe** [comment]
is it fixed?
c

**Comment by wendscheck** [comment]
Yes, it is! 
Perfect
