### ISSUE TITLE
hidden filters? Some entries are missing in the spectra view (xispec integration).

### ISSUE THREAD

**Issue by gieses** [Rappsilber-Laboratory/xiView_container#7]
Hi, 
I uploaded  pseudo* cross-link data and some results are missing. I can image that it is some kind of filtering problem (homo-multimer?). In xiSpec I can see all the results (https://spectrumviewer.org/viewSpectrum.php?db=SvenTest_ISCID). In xiview (ID36) I am missing the peptide identification from scan number 21911, sequence SFLVWVNEEDHLR.

Let me know if you need more information.

* the sample was not cross-linked but searched with cleavable cross-linker options. You could translate this into a cross-linker mass of 0 Da and no-link position.

**Comment by colin-combe** [comment]
i think currently only stuff with a link position is loaded, so yes, hidden filters of sorts

**Comment by gieses** [comment]
Actually... just thought about this again and having this kind of data in xiview somehow defeats it's purpose? I think uploading (and sharing) it via xispec is the better way to go.

**Comment by colin-combe** [comment]
@gieses - i think one difference between the xiSpec and xiView websites is that with xiView there is the possibility of drawing scatterplots, etc, even for the linears.

This isn't available at the moment but adding scatterplots and histograms to the 'validation page' can be done with a quick hack (I've tested).

**Comment by colin-combe** [comment]
it should be that linears are now loaded in xiView and visible via the "Spectra Only" link on the Data Upload page (equivalent to validation page in lab version)
