### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by feiyur** [Rappsilber-Laboratory/xiView_container#72]
Can not creat a new account?

**Comment by colin-combe** [comment]
ok... I just tested it (i.e. account creation at https://xiview.org) and it worked for me.
you'll need to provide a bit more info on what happened - did you receive the email with the confirmation link in it?

**Comment by feiyur** [comment]
Thanks so much for your quick reply!

I filled  the form like this:

[cid:02002147-c289-4016-bf94-7e0318d7303f]
After submitting, this page appeared  :(

[cid:08356df5-7e30-4a44-a966-accfafa16e46]
________________________________
发件人: Colin <notifications@github.com>
发送时间: 2020年8月4日 19:02
收件人: Rappsilber-Laboratory/xiView_container <xiView_container@noreply.github.com>
抄送: feiyur <chem_pengchao@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [Rappsilber-Laboratory/xiView_container] Account (#72)


ok... I just tested it (i.e. account creation at https://xiview.org) and it worked for me.
you'll need to provide a bit more info on what happened - did you receive the email with the confirmation link in it?

―

**Comment by colin-combe** [comment]
I see. The Google recaptcha isn't working for you.
I'll remove it and update this issue to let you know.

**Comment by feiyur** [comment]
Thanks a lot!

**Comment by colin-combe** [comment]
Sorry feiyur - I didn't get this done yet. I haven't forgotten and do intend to remove all the google stuff...

**Comment by feiyur** [comment]
Hi，Colin：

Thanks so much for your efforts. I am still waiting for your solution. We really want to try xiVIEW. Waiting for your good news.

在 2020年9月9日，22:25，Colin <notifications@github.com> 写道：

﻿

Sorry feiyur - I didn't get this done yet. I haven't forgotten and do intend to remove all the google stuff...

**Comment by colin-combe** [comment]
Hi feiyur,
try emailing me at colin.combe@ed.ac.uk - if I get your email I will create an account for you and send you the login details.

This is the quickest way I can make this work for you in the short term (I will be taking a holiday so that will further delay getting rid of the google stuff).

Colin
