### ISSUE TITLE
Crosslinks not displaying properly

### ISSUE THREAD

**Issue by KatSUtrecht** [Rappsilber-Laboratory/xiView_container#79]
![image](https://user-images.githubusercontent.com/83377044/116481512-9b9ef480-a883-11eb-814f-8158e4efca75.png)

**Comment by colin-combe** [comment]
yes - I can confirm that these crosslinks are not displaying properly

I would need to know more about how it happened to fix it. Is this from a file you uploaded to crosslinkviewer.org? If so, you could email me the link to the page and I'll test it. (colin.combe@ed.ac.uk) You can also post the link here, though that means everyone can see your data.

Other info that might help - what browser were you using? does it fix itself if you change the protein to a circle and then back to a bar? Do you know if you did something specific to make it happen? Is it always links to that same protein that are broken? 

cheers,
Colin

**Comment by colin-combe** [comment]
(sorted out)

**Comment by KatSUtrecht** [comment]
Hi Colin,

I’ve been trying to analyse some xlink data using XiVIEW (in particular the export pseudobonds, circular plot and 3D view functions are very useful) but am having a couple of issues. So, the crosslinked residues display correctly in the match table (i.e. all should be either K-K or K-N-terminus bonds) but when I use the 3D view or circular plots they are showing as links to different redisues (see attached screen shots). Is there something in my data that is causing this? I’ve attached my csv file for reference. Are you able to help me in any way?

Kind regards,
Kat

                                                                  ***@***.***D7459F.3661E1A0] ***@***.***D7459E.7EEF4BC0]

**Comment by KatSUtrecht** [comment]
Hi Colin,

Thanks for getting back to me. The Uniprot acc. #s in the search database fasta were obtained directly from Uniprot. The linked residues in the csv correspond to the correct residues in the uniprot sequence, so I don’t think this is the issue. The links are also correctly assigned to lysine residues in the XiVIEW match table, just not in the circular view or 3d views, so unless these plots are somehow generated using different sequences I don’t know how this is possible.

Thanks,
Katherine

**Comment by colin-combe** [comment]
Ok, that doesn't sound right. I wont be able to have a proper look at what's happening until thursday. I'll get back to you then,
Cheers,
C

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KatSUtrecht** [comment]
Great, thank you!

**Comment by colin-combe** [comment]
(@KatSUtrecht  - I emailed u yesterday to say I can't access the csv file to test it)
