### ISSUE TITLE
Incorporate Crosslink Quantification

### ISSUE THREAD

**Issue by xLinkKnight** [Rappsilber-Laboratory/xiView_container#84]
Feature Addition - Allow for the visualization of crosslink quantification information

Our group has been doing a lot more relative quantification experiments involving DSSO/DMTMM and TMT. Our primary search engine is XlinkX in PD. It would advantageous if there was a way to visualize the change in crosslink abundance through xiView. Could connections shown in the network map, circle plot, and PDB structure view be shown differently based on change in abundance? An example would be to change the color (positive or negative change) and thickness (gradient, fold change). These parameters can be generated by the user and added as columns in the uploaded spreadsheet.

**Comment by colin-combe** [comment]
there is some support for this - from the top main menu click IMPORT > EDGE METADATA
(see https://xiview.org/xidocs/html/import/crossmeta.html)
let me know if you have problems,
cheers,
colin

**Comment by xLinkKnight** [comment]
Thank you for the guide. I just have one problem concerning the processing/handling of the hex color value. 

I used a hex color value which corresponds to the abundance fold change of a given crosslink within my protein complex. The values I've used are as follows:

```
#FA9C9E
#FA9FA1
#FCF9FC
#FAA5A7
#FA9496
#FAAFB2
#FAA8AB
#FA9EA0
#5A8AC6
#5A8AC6
#5A8AC6
#F1F4FB
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
```
However, I only see the following once loaded into xiView:

```
#5A8AC6
#5A8AC6
#FCF9FC
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
#5A8AC6
```

May I ask why some colors (red) are omitted or switched to more "blue" values? Please let me know if I'm doing something wrong. Thanks.

**Comment by colin-combe** [comment]
ok... that sounds pretty weird, something may be broken, i'll check.

I'll probably need to test by using your data and your CSV file of colours. You might not want to share the data (or the link to the data) on GitHub so you can email me at colin.combe@ed.ac.uk about how to proceed. 

Its likely to be next week before I look at this,

cheers,
Colin

**Comment by xLinkKnight** [comment]
I've attached the files. Thank you.

[HemoglobinOnly_Script.csv](https://github.com/Rappsilber-Laboratory/xiView_container/files/7943361/HemoglobinOnly_Script.csv)
[Hb_ProteinOnly.txt](https://github.com/Rappsilber-Laboratory/xiView_container/files/7943364/Hb_ProteinOnly.txt)

**Comment by colin-combe** [comment]
Hi,

If you rename the columns 'AbsPos1' and 'AbsPos2' to 'SeqPos 1' and 'SeqPos 2' in the file when you upload it as edge metadata (https://xiview.org/xidocs/html/import/crossmeta.html)  then do you get the results you expect?

I realise this is a bit confusing - you have those columns named correctly for uploading our most minimal CSV format for crosslink data, but they're named differently when uploading link metadata.

I think you're using the same file as your data upload and your edge meta data - that should be fine I think. It would be better if xiVIEW read the metadata out of the CSV file and it was already there for you.

When the column names where wrong it was taking it as edge metadata at the PPI level which is why you got funny looking results.

Ask if further questions,
cheers,
Col

**Comment by colin-combe** [comment]
(with the edge metadata uploaded you should also be able to select "Quantitiation" from the Legend panel and have a range slider for controlling colours based on quantitation data)

**Comment by xLinkKnight** [comment]
That worked! It didn't occur to me that the column naming scheme might be different for the crosslink and metadata files.

crosslink column header:
```Protein1 | AbsPos1 | Protein2 | AbsPos2 | Score | Quantitation | Fixed Colour``` (last two columns are redundant)

metadata header:
```Protein 1 | SeqPos 1 | Protein 2 | SeqPos 2 | Quantitation | Fixed Colour```

Thank you.

**Comment by colin-combe** [comment]
>  It didn't occur to me that the column naming scheme might be different for the crosslink and metadata files
yeah... it doesn't make a whole lot of sense now that i look at it
