### ISSUE TITLE
Error: a float is required

### ISSUE THREAD

**Issue by michabirklbauer** [Rappsilber-Laboratory/xiView_container#94]
Hey,

I am currently trying to analyse some data but get the following error message:

log id: fa5c13j5881k166fvb8ismf81d_1666272254.log (include this in the github issue)
error type: Error
message: a float is required
id: undefined

I have checked that my csv contains all the columns required and checked that the fasta is valid. The csv contains a lot of ambigous links where peptides are found in more then one protein, maybe that is a problem? I made sure however that the crosslink positions and protein identifiers are delimited by semi colons as described on your minimal csv setup.

I have attached the csv and fasta in question. Maybe anyone can help out? Thanks in advance!
[test.csv.txt](https://github.com/Rappsilber-Laboratory/xiView_container/files/9831382/test.csv.txt)
[test.fasta.txt](https://github.com/Rappsilber-Laboratory/xiView_container/files/9831383/test.fasta.txt)

**Comment by colin-combe** [comment]
Hi - sorry - this slipped through the net...

It is a bug with xiVIEW. 

Is it fixed now?

**Comment by michabirklbauer** [comment]
Yes, everything works now! Thanks for the help!
